import type { ProductSeedInput } from '../types'

export const clifBarProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 250,
    carbsG: 44,
    fatG: 5,
    flavor: 'Chocolate Chip',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 10,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-chocolate',
    sodiumMg: 150,
    sugarG: 21
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 250,
    carbsG: 42,
    fatG: 6,
    flavor: 'Crunchy Peanut Butter',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 11,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-peanut',
    sodiumMg: 200,
    sugarG: 21
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 240,
    carbsG: 43,
    fatG: 5,
    flavor: 'Oatmeal Raisin Walnut',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 9,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-oatmeal',
    sodiumMg: 150,
    sugarG: 22
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 250,
    carbsG: 43,
    fatG: 6,
    flavor: 'White Chocolate Macadamia',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 9,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-white-chocolate',
    sodiumMg: 150,
    sugarG: 22
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 240,
    carbsG: 44,
    fatG: 4,
    flavor: 'Chocolate Brownie',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 10,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-brownie',
    sodiumMg: 150,
    sugarG: 21
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 250,
    carbsG: 44,
    fatG: 5,
    flavor: 'Blueberry Crisp',
    form: 'bar',
    name: 'Clif Bar',
    notes: 'Original energy bar',
    proteinG: 10,
    servingSize: 68,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bar-blueberry',
    sodiumMg: 150,
    sugarG: 21
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Citrus',
    form: 'chew',
    name: 'Clif Bloks',
    notes: '6 chews per package',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-citrus',
    sodiumMg: 70,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Strawberry',
    form: 'chew',
    name: 'Clif Bloks',
    notes: '6 chews per package',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-strawberry',
    sodiumMg: 70,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Mountain Berry',
    form: 'chew',
    name: 'Clif Bloks',
    notes: '6 chews per package',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-mountain-berry',
    sodiumMg: 70,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Margarita',
    form: 'chew',
    name: 'Clif Bloks',
    notes: '6 chews per package - extra sodium',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-margarita',
    sodiumMg: 140,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: 50,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Black Cherry',
    form: 'chew',
    name: 'Clif Bloks',
    notes: 'With 50mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-cherry',
    sodiumMg: 70,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: 25,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Tropical Punch',
    form: 'chew',
    name: 'Clif Bloks',
    notes: 'With 25mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-bloks-tropical',
    sodiumMg: 70,
    sugarG: 24
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: 50,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Mocha',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Organic energy gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-mocha',
    sodiumMg: 60,
    sugarG: 12
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: 25,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Chocolate',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Organic energy gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-chocolate',
    sodiumMg: 60,
    sugarG: 12
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: 25,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Organic energy gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-citrus',
    sodiumMg: 60,
    sugarG: 12
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Vanilla',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Caffeine-free gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-vanilla',
    sodiumMg: 60,
    sugarG: 12
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Razz',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Caffeine-free gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-razz',
    sodiumMg: 60,
    sugarG: 12
  },
  {
    brandSlug: 'clif-bar',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Strawberry',
    form: 'gel',
    name: 'Clif Shot Gel',
    notes: 'Caffeine-free gel',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'clif-shot-gel-strawberry',
    sodiumMg: 60,
    sugarG: 12
  }
]
