import type { ProductSeedInput } from '../types'

export const enervitProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 53,
    carbsG: 13,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Enervitene Sport Gel',
    notes: 'Compact gel',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'enervitene-gel-orange',
    sodiumMg: 30,
    sugarG: 6
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 53,
    carbsG: 13,
    fatG: 0,
    flavor: 'Lemon',
    form: 'gel',
    name: 'Enervitene Sport Gel',
    notes: 'Compact gel',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'enervitene-gel-lemon',
    sodiumMg: 30,
    sugarG: 6
  },
  {
    brandSlug: 'enervit',
    caffeineMg: 25,
    calories: 53,
    carbsG: 13,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Enervitene Sport Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'enervitene-gel-cola',
    sodiumMg: 30,
    sugarG: 6
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 27,
    carbsG: 6.5,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Enervitene Sport Gel One Hand',
    notes: 'Easy squeeze gel',
    proteinG: 0,
    servingSize: 12.5,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'enervitene-gel-one-hand',
    sodiumMg: 15,
    sugarG: 3
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 120,
    carbsG: 30,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Enervit C2:1Pro',
    notes: '30g carbs, 2:1 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'c21pro-gel-orange',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 120,
    carbsG: 30,
    fatG: 0,
    flavor: 'Lemon',
    form: 'gel',
    name: 'Enervit C2:1Pro',
    notes: '30g carbs, 2:1 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'c21pro-gel-lemon',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'enervit',
    caffeineMg: 50,
    calories: 120,
    carbsG: 30,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Enervit C2:1Pro Caffeine',
    notes: 'With 50mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'c21pro-gel-caffeine',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 155,
    carbsG: 23,
    fatG: 4,
    flavor: 'Double Cacao',
    form: 'bar',
    name: 'Power Sport Bar',
    notes: 'Performance bar',
    proteinG: 5,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'power-sport-bar-cacao',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 155,
    carbsG: 23,
    fatG: 4,
    flavor: 'Lemon Cream',
    form: 'bar',
    name: 'Power Sport Bar',
    notes: 'Performance bar',
    proteinG: 5,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'power-sport-bar-lemon',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 110,
    carbsG: 27,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Isotonic Drink',
    notes: 'Isotonic formula',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'isotonic-drink-lemon',
    sodiumMg: 200,
    sugarG: 14
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 110,
    carbsG: 27,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Isotonic Drink',
    notes: 'Isotonic formula',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'isotonic-drink-orange',
    sodiumMg: 200,
    sugarG: 14
  },
  {
    brandSlug: 'enervit',
    caffeineMg: null,
    calories: 170,
    carbsG: 43,
    fatG: 0,
    flavor: 'Neutral',
    form: 'drink_mix',
    name: 'Carbo Flow',
    notes: 'High carb drink mix',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'carbo-flow',
    sodiumMg: 150,
    sugarG: 21
  }
]
