import type { ProductSeedInput } from '../types'

export const guEnergyProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'gu-energy',
    caffeineMg: 20,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Salted Caramel',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Original GU gel formula',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-salted-caramel',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 20,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Chocolate Outrage',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Original GU gel formula',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-chocolate',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Tri-Berry',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Caffeine-free',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-tri-berry',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Vanilla Bean',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Caffeine-free',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-vanilla',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Strawberry Banana',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Caffeine-free',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-strawberry-banana',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Mandarin Orange',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Caffeine-free',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-mandarin',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 20,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Lemon Sublime',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-lemon',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 40,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Espresso Love',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Double caffeine',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-espresso',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 40,
    calories: 100,
    carbsG: 22,
    fatG: 0,
    flavor: 'Jet Blackberry',
    form: 'gel',
    name: 'Energy Gel Jet Blackberry',
    notes: 'Double caffeine formula',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-jet-blackberry',
    sodiumMg: 55,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 35,
    calories: 100,
    carbsG: 21,
    fatG: 0,
    flavor: 'Cherry Lime',
    form: 'gel',
    name: 'Roctane Ultra Endurance Gel',
    notes: 'Premium formula with amino acids',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'roctane-gel-cherry',
    sodiumMg: 125,
    sugarG: 5
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 35,
    calories: 100,
    carbsG: 21,
    fatG: 0,
    flavor: 'Vanilla Orange',
    form: 'gel',
    name: 'Roctane Ultra Endurance Gel',
    notes: 'Premium formula with amino acids',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'roctane-gel-vanilla',
    sodiumMg: 125,
    sugarG: 5
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 35,
    calories: 100,
    carbsG: 21,
    fatG: 0,
    flavor: 'Sea Salt Chocolate',
    form: 'gel',
    name: 'Roctane Ultra Endurance Gel',
    notes: 'Premium formula with amino acids',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'roctane-gel-sea-salt',
    sodiumMg: 125,
    sugarG: 5
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 100,
    carbsG: 21,
    fatG: 0,
    flavor: 'Blueberry Pomegranate',
    form: 'gel',
    name: 'Roctane Ultra Endurance Gel',
    notes: 'Caffeine-free Roctane',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'roctane-gel-blueberry',
    sodiumMg: 125,
    sugarG: 5
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 20,
    calories: 90,
    carbsG: 23,
    fatG: 0,
    flavor: 'Watermelon',
    form: 'chew',
    name: 'Energy Chews',
    notes: '4 chews per serving',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-watermelon',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 90,
    carbsG: 23,
    fatG: 0,
    flavor: 'Strawberry',
    form: 'chew',
    name: 'Energy Chews',
    notes: '4 chews per serving, caffeine-free',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-strawberry',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 90,
    carbsG: 23,
    fatG: 0,
    flavor: 'Orange',
    form: 'chew',
    name: 'Energy Chews',
    notes: '4 chews per serving, caffeine-free',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-orange',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 40,
    calories: 90,
    carbsG: 23,
    fatG: 0,
    flavor: 'Blueberry Pomegranate',
    form: 'chew',
    name: 'Energy Chews',
    notes: '4 chews per serving, with caffeine',
    proteinG: 0,
    servingSize: 34,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-blueberry-pom',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 10,
    carbsG: 2,
    fatG: 0,
    flavor: 'Lemon Lime',
    form: 'chew',
    name: 'Hydration Drink Tabs',
    notes: 'Zero calorie electrolyte tablets',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-tabs-lemon',
    sodiumMg: 320,
    sugarG: 1
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 10,
    carbsG: 2,
    fatG: 0,
    flavor: 'Strawberry Lemonade',
    form: 'chew',
    name: 'Hydration Drink Tabs',
    notes: 'Zero calorie electrolyte tablets',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-tabs-strawberry',
    sodiumMg: 320,
    sugarG: 1
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 10,
    carbsG: 2,
    fatG: 0,
    flavor: 'Orange',
    form: 'chew',
    name: 'Hydration Drink Tabs',
    notes: 'Zero calorie electrolyte tablets',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-tabs-orange',
    sodiumMg: 320,
    sugarG: 1
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 150,
    carbsG: 22,
    fatG: 5,
    flavor: 'Salted Chocolate',
    form: 'solid',
    name: 'Energy Stroopwafel',
    notes: 'Dutch-style waffle snack',
    proteinG: 2,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'stroopwafel-chocolate',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 20,
    calories: 150,
    carbsG: 22,
    fatG: 5,
    flavor: 'Caramel Coffee',
    form: 'solid',
    name: 'Energy Stroopwafel',
    notes: 'Dutch-style waffle snack with caffeine',
    proteinG: 2,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'stroopwafel-caramel',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 150,
    carbsG: 22,
    fatG: 5,
    flavor: 'Wild Berry',
    form: 'solid',
    name: 'Energy Stroopwafel',
    notes: 'Dutch-style waffle snack',
    proteinG: 2,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'stroopwafel-wild-berry',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Lemon Lime',
    form: 'drink_mix',
    name: 'Hydration Drink Mix',
    notes: 'Electrolyte drink mix',
    proteinG: 0,
    servingSize: 24,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-mix-lemon',
    sodiumMg: 320,
    sugarG: 6
  },
  {
    brandSlug: 'gu-energy',
    caffeineMg: 35,
    calories: 250,
    carbsG: 59,
    fatG: 0,
    flavor: 'Lemon Berry',
    form: 'drink_mix',
    name: 'Roctane Energy Drink Mix',
    notes: 'Premium endurance drink',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'roctane-drink-lemon',
    sodiumMg: 500,
    sugarG: 12
  }
]
