import type { ProductSeedInput } from '../types'

export const hammerNutritionProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Vanilla',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'No simple sugars',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-vanilla',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Chocolate',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'No simple sugars',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-chocolate',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Raspberry',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'No simple sugars',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-raspberry',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Banana',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'No simple sugars',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-banana',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Apple Cinnamon',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'No simple sugars',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-apple',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: 50,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Tropical',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-tropical',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: 50,
    calories: 90,
    carbsG: 22,
    fatG: 0,
    flavor: 'Espresso',
    form: 'gel',
    name: 'Hammer Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-gel-espresso',
    sodiumMg: 20,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 210,
    carbsG: 27,
    fatG: 8,
    flavor: 'Chocolate Chip',
    form: 'bar',
    name: 'Hammer Bar',
    notes: 'Endurance bar',
    proteinG: 7,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-bar-chocolate',
    sodiumMg: 20,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 210,
    carbsG: 27,
    fatG: 8,
    flavor: 'Almond Raisin',
    form: 'bar',
    name: 'Hammer Bar',
    notes: 'Endurance bar',
    proteinG: 7,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-bar-almond',
    sodiumMg: 20,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 210,
    carbsG: 27,
    fatG: 8,
    flavor: 'Oatmeal Apple',
    form: 'bar',
    name: 'Hammer Bar',
    notes: 'Endurance bar',
    proteinG: 7,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hammer-bar-oatmeal',
    sodiumMg: 20,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Lemon Lime',
    form: 'drink_mix',
    name: 'Heed',
    notes: 'No simple sugars drink',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'heed-lemon',
    sodiumMg: 100,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Mandarin Orange',
    form: 'drink_mix',
    name: 'Heed',
    notes: 'No simple sugars drink',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'heed-mandarin',
    sodiumMg: 100,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Melon',
    form: 'drink_mix',
    name: 'Heed',
    notes: 'No simple sugars drink',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'heed-melon',
    sodiumMg: 100,
    sugarG: 2
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 200,
    carbsG: 39,
    fatG: 2,
    flavor: 'Orange Vanilla',
    form: 'drink_mix',
    name: 'Perpetuem',
    notes: 'Ultra-endurance fuel',
    proteinG: 7,
    servingSize: 54,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'perpetuem-orange',
    sodiumMg: 150,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 200,
    carbsG: 39,
    fatG: 2,
    flavor: 'Strawberry Vanilla',
    form: 'drink_mix',
    name: 'Perpetuem',
    notes: 'Ultra-endurance fuel',
    proteinG: 7,
    servingSize: 54,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'perpetuem-strawberry',
    sodiumMg: 150,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: 25,
    calories: 200,
    carbsG: 39,
    fatG: 2,
    flavor: 'Caffè Latte',
    form: 'drink_mix',
    name: 'Perpetuem',
    notes: 'With caffeine',
    proteinG: 7,
    servingSize: 54,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'perpetuem-caffeine',
    sodiumMg: 150,
    sugarG: 4
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'capsule',
    name: 'Endurolytes',
    notes: 'Electrolyte capsules',
    proteinG: 0,
    servingSize: 1,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurolytes-capsules',
    sodiumMg: 100,
    sugarG: 0
  },
  {
    brandSlug: 'hammer-nutrition',
    caffeineMg: null,
    calories: 10,
    carbsG: 2,
    fatG: 0,
    flavor: 'Lemon Lime',
    form: 'chew',
    name: 'Endurolytes Fizz',
    notes: 'Effervescent electrolytes',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurolytes-fizz-lemon',
    sodiumMg: 200,
    sugarG: 0
  }
]
