import type { ProductSeedInput } from '../types'

export const high5ProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Easy-open sachet',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-orange',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Berry',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Easy-open sachet',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-berry',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Banana',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Easy-open sachet',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-banana',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Apple',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Easy-open sachet',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-apple',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: 30,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Citrus Burst',
    form: 'gel',
    name: 'Energy Gel Caffeine',
    notes: 'With 30mg caffeine',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-caffeine-citrus',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: 30,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Espresso',
    form: 'gel',
    name: 'Energy Gel Caffeine',
    notes: 'With 30mg caffeine',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-caffeine-espresso',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Energy Gel Aqua',
    notes: 'Liquid consistency - no water needed',
    proteinG: 0,
    servingSize: 66,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-aqua-orange',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Berry',
    form: 'gel',
    name: 'Energy Gel Aqua',
    notes: 'Liquid consistency - no water needed',
    proteinG: 0,
    servingSize: 66,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-aqua-berry',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: 30,
    calories: 92,
    carbsG: 23,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Energy Gel Aqua Caffeine',
    notes: 'Aqua gel with caffeine',
    proteinG: 0,
    servingSize: 66,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-aqua-caffeine',
    sodiumMg: 50,
    sugarG: 5
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 200,
    carbsG: 38,
    fatG: 4,
    flavor: 'Banana',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Real fruit energy bar',
    proteinG: 4,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-banana',
    sodiumMg: 25,
    sugarG: 18
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 200,
    carbsG: 38,
    fatG: 4,
    flavor: 'Caramel',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Real fruit energy bar',
    proteinG: 4,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-caramel',
    sodiumMg: 25,
    sugarG: 18
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 200,
    carbsG: 38,
    fatG: 4,
    flavor: 'Berry',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Real fruit energy bar',
    proteinG: 4,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-berry',
    sodiumMg: 25,
    sugarG: 18
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 7,
    carbsG: 1,
    fatG: 0,
    flavor: 'Berry',
    form: 'chew',
    name: 'Zero Electrolyte Drink',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'zero-tabs-berry',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 7,
    carbsG: 1,
    fatG: 0,
    flavor: 'Citrus',
    form: 'chew',
    name: 'Zero Electrolyte Drink',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'zero-tabs-citrus',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 7,
    carbsG: 1,
    fatG: 0,
    flavor: 'Tropical',
    form: 'chew',
    name: 'Zero Electrolyte Drink',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'zero-tabs-tropical',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 176,
    carbsG: 44,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Energy Source',
    notes: '2:1 glucose:fructose energy drink',
    proteinG: 0,
    servingSize: 47,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-source-orange',
    sodiumMg: 100,
    sugarG: 10
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 176,
    carbsG: 44,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Energy Source',
    notes: '2:1 glucose:fructose energy drink',
    proteinG: 0,
    servingSize: 47,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-source-citrus',
    sodiumMg: 100,
    sugarG: 10
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 216,
    carbsG: 54,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Energy Source Xtreme',
    notes: 'Higher carb formula',
    proteinG: 0,
    servingSize: 58,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-source-xtreme',
    sodiumMg: 125,
    sugarG: 12
  },
  {
    brandSlug: 'high5',
    caffeineMg: null,
    calories: 180,
    carbsG: 27,
    fatG: 2,
    flavor: 'Chocolate',
    form: 'powder',
    name: '4:1 Recovery',
    notes: 'Recovery shake',
    proteinG: 15,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'recovery-41-chocolate',
    sodiumMg: 100,
    sugarG: 10
  }
]
