import type { ProductSeedInput } from '../types'

export const honeyStingerProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Gold',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'Honey-based gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-gold',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Strawberry Kiwi',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'Honey-based gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-strawberry',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Fruit Smoothie',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'Honey-based gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-fruit-smoothie',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Acai & Pomegranate',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'Honey-based gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-acai',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Mango Orange',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'Honey-based gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-mango',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: 32,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Chocolate',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-chocolate',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: 32,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Ginsting',
    form: 'gel',
    name: 'Organic Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'organic-gel-ginsting',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 6,
    flavor: 'Honey',
    form: 'solid',
    name: 'Organic Stinger Waffle',
    notes: 'Organic waffle',
    proteinG: 1,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-honey',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 6,
    flavor: 'Vanilla & Chocolate',
    form: 'solid',
    name: 'Organic Stinger Waffle',
    notes: 'Organic waffle',
    proteinG: 1,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-vanilla',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 6,
    flavor: 'Caramel',
    form: 'solid',
    name: 'Organic Stinger Waffle',
    notes: 'Organic waffle',
    proteinG: 1,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-caramel',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 6,
    flavor: 'Cinnamon',
    form: 'solid',
    name: 'Organic Stinger Waffle',
    notes: 'Organic waffle',
    proteinG: 1,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-cinnamon',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: 32,
    calories: 140,
    carbsG: 21,
    fatG: 6,
    flavor: 'Ginsting',
    form: 'solid',
    name: 'Organic Stinger Waffle',
    notes: 'With caffeine',
    proteinG: 1,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-ginsting',
    sodiumMg: 50,
    sugarG: 11
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Orange Blossom',
    form: 'chew',
    name: 'Organic Energy Chews',
    notes: 'Honey chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chews-orange',
    sodiumMg: 80,
    sugarG: 27
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Cherry Blossom',
    form: 'chew',
    name: 'Organic Energy Chews',
    notes: 'Honey chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chews-cherry',
    sodiumMg: 80,
    sugarG: 27
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Lime-Ade',
    form: 'chew',
    name: 'Organic Energy Chews',
    notes: 'Honey chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chews-lime',
    sodiumMg: 80,
    sugarG: 27
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Fruit Smoothie',
    form: 'chew',
    name: 'Organic Energy Chews',
    notes: 'Honey chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chews-fruit-smoothie',
    sodiumMg: 80,
    sugarG: 27
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Stingerita',
    form: 'chew',
    name: 'Organic Energy Chews',
    notes: 'Extra sodium',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chews-stingerita',
    sodiumMg: 160,
    sugarG: 27
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 200,
    carbsG: 29,
    fatG: 7,
    flavor: 'Peanut Butter & Honey',
    form: 'bar',
    name: 'Cracker Bar',
    notes: 'Savory snack bar',
    proteinG: 5,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'cracker-bar-peanut',
    sodiumMg: 150,
    sugarG: 14
  },
  {
    brandSlug: 'honey-stinger',
    caffeineMg: null,
    calories: 200,
    carbsG: 29,
    fatG: 7,
    flavor: 'Almond Butter & Honey',
    form: 'bar',
    name: 'Cracker Bar',
    notes: 'Savory snack bar',
    proteinG: 5,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'cracker-bar-almond',
    sodiumMg: 150,
    sugarG: 14
  }
]
