import type { ProductSeedInput } from '../types'

export const humaGelProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'huma-gel',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Strawberries',
    form: 'gel',
    name: 'Chia Energy Gel',
    notes: 'Chia-based gel',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-strawberry',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Mangoes',
    form: 'gel',
    name: 'Chia Energy Gel',
    notes: 'Chia-based gel',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-mango',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Apples & Cinnamon',
    form: 'gel',
    name: 'Chia Energy Gel',
    notes: 'Chia-based gel',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-apple',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Lemonade',
    form: 'gel',
    name: 'Chia Energy Gel',
    notes: 'Chia-based gel',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-lemonade',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: null,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Blueberries',
    form: 'gel',
    name: 'Chia Energy Gel',
    notes: 'Chia-based gel',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-blueberry',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: 25,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Chocolate',
    form: 'gel',
    name: 'Chia Energy Gel Plus',
    notes: 'With caffeine',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-plus-chocolate',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'huma-gel',
    caffeineMg: 50,
    calories: 100,
    carbsG: 22,
    fatG: 1,
    flavor: 'Espresso',
    form: 'gel',
    name: 'Chia Energy Gel Plus',
    notes: 'With caffeine',
    proteinG: 1,
    servingSize: 39,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'chia-gel-plus-espresso',
    sodiumMg: 50,
    sugarG: 12
  }
]
