import type { ProductSeedInput } from '../types'

export const maurtenProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'Gel 100',
    notes: 'Hydrogel technology for easy absorption',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel-100',
    sodiumMg: 35,
    sugarG: 12.5
  },
  {
    brandSlug: 'maurten',
    caffeineMg: 100,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'Gel 100 Caf 100',
    notes: 'With 100mg caffeine',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel-100-caf-100',
    sodiumMg: 35,
    sugarG: 12.5
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'Gel 160',
    notes: 'Higher carb version for intense efforts',
    proteinG: 0,
    servingSize: 65,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel-160',
    sodiumMg: 55,
    sugarG: 20
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'Drink Mix 160',
    notes: 'Hydrogel drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'drink-mix-160',
    sodiumMg: 80,
    sugarG: 20
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 320,
    carbsG: 80,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'Drink Mix 320',
    notes: 'High carb hydrogel drink mix',
    proteinG: 0,
    servingSize: 80,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'drink-mix-320',
    sodiumMg: 160,
    sugarG: 40
  },
  {
    brandSlug: 'maurten',
    caffeineMg: 100,
    calories: 320,
    carbsG: 80,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'Drink Mix 320 Caf 100',
    notes: 'High carb with caffeine',
    proteinG: 0,
    servingSize: 80,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'drink-mix-320-caf-100',
    sodiumMg: 160,
    sugarG: 40
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 225,
    carbsG: 56,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'solid',
    name: 'Solid 225',
    notes: 'Solid fuel bar with hydrogel technology',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'solid-225',
    sodiumMg: 90,
    sugarG: 28
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'solid',
    name: 'Solid 160',
    notes: 'Smaller solid fuel option',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'solid-160',
    sodiumMg: 65,
    sugarG: 20
  },
  {
    brandSlug: 'maurten',
    caffeineMg: 100,
    calories: 225,
    carbsG: 56,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'solid',
    name: 'Solid 225 Caf 100',
    notes: 'Solid with 100mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'solid-225-caf-100',
    sodiumMg: 90,
    sugarG: 28
  },
  {
    brandSlug: 'maurten',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'capsule',
    name: 'Bicarb System',
    notes: 'Sodium bicarbonate loading system',
    proteinG: 0,
    servingSize: 5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'bicarb-system',
    sodiumMg: 1680,
    sugarG: 0
  }
]
