import type { ProductSeedInput } from '../types'

export const mnstyrProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Energy Gel 30',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-30-citrus',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Berry',
    form: 'gel',
    name: 'Energy Gel 30',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-30-berry',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Tropical',
    form: 'gel',
    name: 'Energy Gel 30',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-30-tropical',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: 75,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Energy Gel 30 Caffeine',
    notes: '30g carbs with 75mg caffeine',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-30-caffeine-cola',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: 100,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Espresso',
    form: 'gel',
    name: 'Energy Gel 30 Caffeine',
    notes: '30g carbs with 100mg caffeine',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-30-caffeine-espresso',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Energy Gel 45',
    notes: '45g carbs, high carb gel',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-45-citrus',
    sodiumMg: 150,
    sugarG: 22
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Neutral',
    form: 'gel',
    name: 'Energy Gel 45',
    notes: '45g carbs, high carb gel',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-45-neutral',
    sodiumMg: 150,
    sugarG: 22
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 200,
    carbsG: 32,
    fatG: 6,
    flavor: 'Chocolate',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Balanced energy bar',
    proteinG: 4,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-chocolate',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 210,
    carbsG: 30,
    fatG: 8,
    flavor: 'Peanut Butter',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Balanced energy bar',
    proteinG: 5,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-peanut',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 195,
    carbsG: 33,
    fatG: 5,
    flavor: 'Mixed Berry',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Balanced energy bar',
    proteinG: 3,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-berry',
    sodiumMg: 50,
    sugarG: 17
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 150,
    carbsG: 38,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Hydration Mix',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-mix-lemon',
    sodiumMg: 400,
    sugarG: 18
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 150,
    carbsG: 38,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Hydration Mix',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-mix-orange',
    sodiumMg: 400,
    sugarG: 18
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 150,
    carbsG: 38,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'Hydration Mix',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-mix-berry',
    sodiumMg: 400,
    sugarG: 18
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 340,
    carbsG: 90,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Fuel 90',
    notes: '90g carbs per serving',
    proteinG: 0,
    servingSize: 90,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'fuel-90-citrus',
    sodiumMg: 500,
    sugarG: 45
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 340,
    carbsG: 90,
    fatG: 0,
    flavor: 'Neutral',
    form: 'drink_mix',
    name: 'Fuel 90',
    notes: '90g carbs per serving',
    proteinG: 0,
    servingSize: 90,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'fuel-90-neutral',
    sodiumMg: 500,
    sugarG: 45
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 8,
    carbsG: 2,
    fatG: 0,
    flavor: 'Lemon',
    form: 'chew',
    name: 'Electrolyte Tabs',
    notes: 'Zero calorie electrolytes',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'electrolyte-tabs-lemon',
    sodiumMg: 300,
    sugarG: 0
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: null,
    calories: 8,
    carbsG: 2,
    fatG: 0,
    flavor: 'Berry',
    form: 'chew',
    name: 'Electrolyte Tabs',
    notes: 'Zero calorie electrolytes',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'electrolyte-tabs-berry',
    sodiumMg: 300,
    sugarG: 0
  },
  {
    brandSlug: 'mnstyr',
    caffeineMg: 200,
    calories: 15,
    carbsG: 4,
    fatG: 0,
    flavor: 'Citrus',
    form: 'liquid',
    name: 'Caffeine Shot',
    notes: 'High caffeine shot',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'caffeine-shot',
    sodiumMg: 0,
    sugarG: 2
  }
]
