import type { ProductSeedInput } from '../types'

export const naakProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 200,
    carbsG: 25,
    fatG: 7,
    flavor: 'Peanut Butter & Chocolate',
    form: 'bar',
    name: 'Ultra Energy Bar',
    notes: 'Cricket protein bar',
    proteinG: 10,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-bar-peanut',
    sodiumMg: 120,
    sugarG: 10
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 200,
    carbsG: 25,
    fatG: 7,
    flavor: 'Apple Pie',
    form: 'bar',
    name: 'Ultra Energy Bar',
    notes: 'Cricket protein bar',
    proteinG: 10,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-bar-apple',
    sodiumMg: 120,
    sugarG: 10
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 200,
    carbsG: 25,
    fatG: 7,
    flavor: 'Banana Chocolate',
    form: 'bar',
    name: 'Ultra Energy Bar',
    notes: 'Cricket protein bar',
    proteinG: 10,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-bar-banana',
    sodiumMg: 120,
    sugarG: 10
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 5,
    flavor: 'Maple',
    form: 'solid',
    name: 'Ultra Energy Waffle',
    notes: 'Waffle with cricket protein',
    proteinG: 3,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-waffle-maple',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 140,
    carbsG: 21,
    fatG: 5,
    flavor: 'Chocolate',
    form: 'solid',
    name: 'Ultra Energy Waffle',
    notes: 'Waffle with cricket protein',
    proteinG: 3,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-waffle-chocolate',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Maple',
    form: 'gel',
    name: 'Ultra Energy Gel',
    notes: 'Maple syrup gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-gel-maple',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Ultra Energy Gel',
    notes: 'Citrus gel',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-gel-citrus',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'naak',
    caffeineMg: 50,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Espresso',
    form: 'gel',
    name: 'Ultra Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 32,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-gel-espresso',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 150,
    carbsG: 37,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Ultra Energy Drink Mix',
    notes: 'Isotonic drink',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-drink-lemon',
    sodiumMg: 300,
    sugarG: 18
  },
  {
    brandSlug: 'naak',
    caffeineMg: null,
    calories: 150,
    carbsG: 37,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'Ultra Energy Drink Mix',
    notes: 'Isotonic drink',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ultra-drink-berry',
    sodiumMg: 300,
    sugarG: 18
  }
]
