import type { ProductSeedInput } from '../types'

export const nduranzProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Nrgy Unit Gel',
    notes: '45g carbs per gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-gel-orange',
    sodiumMg: 100,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Lemon',
    form: 'gel',
    name: 'Nrgy Unit Gel',
    notes: '45g carbs per gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-gel-lemon',
    sodiumMg: 100,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Neutral',
    form: 'gel',
    name: 'Nrgy Unit Gel',
    notes: '45g carbs per gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-gel-neutral',
    sodiumMg: 100,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: 100,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Nrgy Unit Gel Caffeine',
    notes: '45g carbs with 100mg caffeine',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-gel-caffeine',
    sodiumMg: 100,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Nrgy Unit Drink',
    notes: '45g carbs drink mix',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-drink-orange',
    sodiumMg: 350,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 170,
    carbsG: 45,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Nrgy Unit Drink',
    notes: '45g carbs drink mix',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-drink-lemon',
    sodiumMg: 350,
    sugarG: 22
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 340,
    carbsG: 90,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Nrgy Unit Drink 90',
    notes: '90g carbs drink mix',
    proteinG: 0,
    servingSize: 90,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-drink-90-orange',
    sodiumMg: 700,
    sugarG: 44
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 180,
    carbsG: 30,
    fatG: 5,
    flavor: 'Chocolate',
    form: 'bar',
    name: 'Nrgy Unit Bar',
    notes: 'Energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-bar-chocolate',
    sodiumMg: 80,
    sugarG: 15
  },
  {
    brandSlug: 'nduranz',
    caffeineMg: null,
    calories: 185,
    carbsG: 28,
    fatG: 6,
    flavor: 'Hazelnut',
    form: 'bar',
    name: 'Nrgy Unit Bar',
    notes: 'Energy bar',
    proteinG: 4,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nrgy-bar-hazelnut',
    sodiumMg: 80,
    sugarG: 14
  }
]
