import type { ProductSeedInput } from '../types'

export const neversecondProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'C30 Energy Gel',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-gel-citrus',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Passion Fruit',
    form: 'gel',
    name: 'C30 Energy Gel',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-gel-passion-fruit',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Mango',
    form: 'gel',
    name: 'C30 Energy Gel',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-gel-mango',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: 75,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'C30+ Caffeine Gel',
    notes: '30g carbs with 75mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-caffeine-gel-cola',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: 75,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Espresso',
    form: 'gel',
    name: 'C30+ Caffeine Gel',
    notes: '30g carbs with 75mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-caffeine-gel-espresso',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 360,
    carbsG: 90,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'C90 High Carb Drink Mix',
    notes: '90g carbs per serving',
    proteinG: 0,
    servingSize: 90,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c90-mix-citrus',
    sodiumMg: 250,
    sugarG: 45
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 360,
    carbsG: 90,
    fatG: 0,
    flavor: 'Mango',
    form: 'drink_mix',
    name: 'C90 High Carb Drink Mix',
    notes: '90g carbs per serving',
    proteinG: 0,
    servingSize: 90,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c90-mix-mango',
    sodiumMg: 250,
    sugarG: 45
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'C30 Sports Drink',
    notes: '30g carbs isotonic drink',
    proteinG: 0,
    servingSize: 38,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-drink-citrus',
    sodiumMg: 250,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'C30 Sports Drink',
    notes: '30g carbs isotonic drink',
    proteinG: 0,
    servingSize: 38,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-drink-berry',
    sodiumMg: 250,
    sugarG: 15
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 170,
    carbsG: 30,
    fatG: 4,
    flavor: 'Cocoa',
    form: 'bar',
    name: 'C30 Energy Bar',
    notes: '30g carbs energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-bar-cocoa',
    sodiumMg: 80,
    sugarG: 14
  },
  {
    brandSlug: 'neversecond',
    caffeineMg: null,
    calories: 170,
    carbsG: 30,
    fatG: 4,
    flavor: 'Banana',
    form: 'bar',
    name: 'C30 Energy Bar',
    notes: '30g carbs energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'c30-bar-banana',
    sodiumMg: 80,
    sugarG: 14
  }
]
