import type { ProductSeedInput } from '../types'

export const oteSportsProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 104,
    carbsG: 26,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-lemon',
    sodiumMg: 50,
    sugarG: 13
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 104,
    carbsG: 26,
    fatG: 0,
    flavor: 'Blackcurrant',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-blackcurrant',
    sodiumMg: 50,
    sugarG: 13
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 104,
    carbsG: 26,
    fatG: 0,
    flavor: 'Apple',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-apple',
    sodiumMg: 50,
    sugarG: 13
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 104,
    carbsG: 26,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-orange',
    sodiumMg: 50,
    sugarG: 13
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: 50,
    calories: 104,
    carbsG: 26,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Energy Gel Caffeine',
    notes: 'With 50mg caffeine',
    proteinG: 0,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-caffeine-cola',
    sodiumMg: 50,
    sugarG: 13
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'gel',
    name: 'Super Gel',
    notes: 'High carb gel',
    proteinG: 0,
    servingSize: 66,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'super-gel-lemon',
    sodiumMg: 100,
    sugarG: 20
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 243,
    carbsG: 36,
    fatG: 8,
    flavor: 'Cocoa & Coconut',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-cocoa',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 243,
    carbsG: 36,
    fatG: 8,
    flavor: 'Cherry & Almond',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-cherry',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 162,
    carbsG: 40,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'drink_mix',
    name: 'Energy Drink',
    notes: 'Isotonic drink',
    proteinG: 0,
    servingSize: 43,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-drink-lemon',
    sodiumMg: 200,
    sugarG: 20
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 162,
    carbsG: 40,
    fatG: 0,
    flavor: 'Blackcurrant',
    form: 'drink_mix',
    name: 'Energy Drink',
    notes: 'Isotonic drink',
    proteinG: 0,
    servingSize: 43,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-drink-blackcurrant',
    sodiumMg: 200,
    sugarG: 20
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 8,
    carbsG: 2,
    fatG: 0,
    flavor: 'Lemon',
    form: 'chew',
    name: 'Hydro Tab',
    notes: 'Zero calorie electrolyte',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydro-tab-lemon',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'ote-sports',
    caffeineMg: null,
    calories: 8,
    carbsG: 2,
    fatG: 0,
    flavor: 'Berry',
    form: 'chew',
    name: 'Hydro Tab',
    notes: 'Zero calorie electrolyte',
    proteinG: 0,
    servingSize: 4,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydro-tab-berry',
    sodiumMg: 250,
    sugarG: 0
  }
]
