import type { ProductSeedInput } from '../types'

export const powerbarProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Lemon Lime',
    form: 'gel',
    name: 'PowerGel Original',
    notes: 'Classic energy gel',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-original-lemon',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Strawberry Banana',
    form: 'gel',
    name: 'PowerGel Original',
    notes: 'Classic energy gel',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-original-strawberry',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Vanilla',
    form: 'gel',
    name: 'PowerGel Original',
    notes: 'Classic energy gel',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-original-vanilla',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Chocolate',
    form: 'gel',
    name: 'PowerGel Original',
    notes: 'Classic energy gel',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-original-chocolate',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: 50,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'PowerGel Original Caffeine',
    notes: 'With 50mg caffeine',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-caffeine-cola',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: 50,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Green Apple',
    form: 'gel',
    name: 'PowerGel Original Caffeine',
    notes: 'With 50mg caffeine',
    proteinG: 0,
    servingSize: 41,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-caffeine-green-apple',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Cherry',
    form: 'gel',
    name: 'PowerGel Hydro',
    notes: 'Hydro gel - no water needed',
    proteinG: 0,
    servingSize: 67,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'powergel-hydro-cherry',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: 75,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'PowerGel Hydro',
    notes: 'Hydro gel with caffeine',
    proteinG: 0,
    servingSize: 67,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'powergel-hydro-cola',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 108,
    carbsG: 27,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'PowerGel Hydro',
    notes: 'Hydro gel - no water needed',
    proteinG: 0,
    servingSize: 67,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'powergel-hydro-orange',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 196,
    carbsG: 34,
    fatG: 4,
    flavor: 'Chocolate',
    form: 'bar',
    name: 'Energize Bar',
    notes: 'Energy bar',
    proteinG: 5,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energize-bar-chocolate',
    sodiumMg: 80,
    sugarG: 18
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 196,
    carbsG: 34,
    fatG: 4,
    flavor: 'Berry',
    form: 'bar',
    name: 'Energize Bar',
    notes: 'Energy bar',
    proteinG: 5,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energize-bar-berry',
    sodiumMg: 80,
    sugarG: 18
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 196,
    carbsG: 34,
    fatG: 4,
    flavor: 'Banana Punch',
    form: 'bar',
    name: 'Energize Bar',
    notes: 'Energy bar',
    proteinG: 5,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energize-bar-banana',
    sodiumMg: 80,
    sugarG: 18
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 143,
    carbsG: 23,
    fatG: 4,
    flavor: 'Cacao Crunch',
    form: 'bar',
    name: 'Natural Energy Bar',
    notes: 'Natural ingredients',
    proteinG: 3,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'natural-energy-bar-cacao',
    sodiumMg: 20,
    sugarG: 13
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 143,
    carbsG: 23,
    fatG: 4,
    flavor: 'Strawberry & Cranberry',
    form: 'bar',
    name: 'Natural Energy Bar',
    notes: 'Natural ingredients',
    proteinG: 3,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'natural-energy-bar-strawberry',
    sodiumMg: 20,
    sugarG: 13
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 124,
    carbsG: 31,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Isoactive',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'isoactive-lemon',
    sodiumMg: 250,
    sugarG: 15
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 124,
    carbsG: 31,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Isoactive',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'isoactive-orange',
    sodiumMg: 250,
    sugarG: 15
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: null,
    calories: 178,
    carbsG: 44,
    fatG: 0,
    flavor: 'Raspberry',
    form: 'chew',
    name: 'PowerGel Shots',
    notes: 'Energy chews',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-shots-raspberry',
    sodiumMg: 50,
    sugarG: 22
  },
  {
    brandSlug: 'powerbar',
    caffeineMg: 75,
    calories: 178,
    carbsG: 44,
    fatG: 0,
    flavor: 'Cola',
    form: 'chew',
    name: 'PowerGel Shots',
    notes: 'Energy chews with caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'powergel-shots-cola',
    sodiumMg: 50,
    sugarG: 22
  }
]
