import type { ProductSeedInput } from '../types'

export const precisionHydrationProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 5,
    carbsG: 1,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'chew',
    name: 'PH 250 Tablets',
    notes: 'Low sodium option',
    proteinG: 0,
    servingSize: 4.5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-250-tabs',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 5,
    carbsG: 1,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'chew',
    name: 'PH 500 Tablets',
    notes: 'Moderate sodium',
    proteinG: 0,
    servingSize: 4.5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-500-tabs',
    sodiumMg: 500,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 5,
    carbsG: 1,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'chew',
    name: 'PH 1000 Tablets',
    notes: 'High sodium for heavy sweaters',
    proteinG: 0,
    servingSize: 4.5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-1000-tabs',
    sodiumMg: 1000,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 5,
    carbsG: 1,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'chew',
    name: 'PH 1500 Tablets',
    notes: 'Very high sodium for extreme conditions',
    proteinG: 0,
    servingSize: 4.5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-1500-tabs',
    sodiumMg: 1500,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'PF 30 Gel',
    notes: '30g carbs per gel',
    proteinG: 0,
    servingSize: 51,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'pf-30-gel',
    sodiumMg: 200,
    sugarG: 7
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: 100,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'PF 30 Gel Caffeine',
    notes: '30g carbs with 100mg caffeine',
    proteinG: 0,
    servingSize: 51,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'pf-30-gel-caffeine',
    sodiumMg: 200,
    sugarG: 7
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 226,
    carbsG: 60,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'gel',
    name: 'PF 60 Gel',
    notes: '60g carbs per gel - double serving',
    proteinG: 0,
    servingSize: 102,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'pf-60-gel',
    sodiumMg: 400,
    sugarG: 14
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 347,
    carbsG: 90,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PF 90 Drink Mix',
    notes: '90g carbs per 500ml',
    proteinG: 0,
    servingSize: 93,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'pf-90-mix',
    sodiumMg: 500,
    sugarG: 22
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: 100,
    calories: 347,
    carbsG: 90,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PF 90 Drink Mix Caffeine',
    notes: '90g carbs with 100mg caffeine',
    proteinG: 0,
    servingSize: 93,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'pf-90-mix-caffeine',
    sodiumMg: 500,
    sugarG: 22
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PH 250 Drink Mix',
    notes: 'Low calorie electrolyte mix',
    proteinG: 0,
    servingSize: 12,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-250-mix',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PH 500 Drink Mix',
    notes: 'Low calorie electrolyte mix',
    proteinG: 0,
    servingSize: 12,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-500-mix',
    sodiumMg: 500,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PH 1000 Drink Mix',
    notes: 'Low calorie electrolyte mix',
    proteinG: 0,
    servingSize: 12,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-1000-mix',
    sodiumMg: 1000,
    sugarG: 0
  },
  {
    brandSlug: 'precision-hydration',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'PH 1500 Drink Mix',
    notes: 'Low calorie electrolyte mix',
    proteinG: 0,
    servingSize: 12,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'ph-1500-mix',
    sodiumMg: 1500,
    sugarG: 0
  }
]
