import type { ProductSeedInput } from '../types'

export const sisProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'GO Isotonic Energy Gel',
    notes: 'Isotonic formula - no water needed',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Apple',
    form: 'gel',
    name: 'GO Isotonic Energy Gel',
    notes: 'Isotonic formula - no water needed',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-apple',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'gel',
    name: 'GO Isotonic Energy Gel',
    notes: 'Isotonic formula - no water needed',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-lemon-lime',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Tropical',
    form: 'gel',
    name: 'GO Isotonic Energy Gel',
    notes: 'Isotonic formula - no water needed',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-tropical',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: 75,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Berry',
    form: 'gel',
    name: 'GO Isotonic Energy Gel + Caffeine',
    notes: 'With 75mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-caffeine-berry',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: 75,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'GO Isotonic Energy Gel + Caffeine',
    notes: 'With 75mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-caffeine-cola',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: 150,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'GO Isotonic Energy Gel + Caffeine',
    notes: 'With 150mg caffeine - double shot',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-isotonic-gel-caffeine-citrus',
    sodiumMg: 10,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Salted Strawberry',
    form: 'gel',
    name: 'GO Energy + Electrolyte Gel',
    notes: 'Added electrolytes for hot conditions',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-energy-electrolyte-gel',
    sodiumMg: 118,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 87,
    carbsG: 22,
    fatG: 0,
    flavor: 'Lemon & Mint',
    form: 'gel',
    name: 'GO Energy + Electrolyte Gel',
    notes: 'Added electrolytes for hot conditions',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'go-energy-electrolyte-gel-lemon',
    sodiumMg: 118,
    sugarG: 1
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 164,
    carbsG: 40,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Beta Fuel Gel',
    notes: '40g carbs with 1:0.8 glucose:fructose ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'beta-fuel-gel-orange',
    sodiumMg: 35,
    sugarG: 8
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 164,
    carbsG: 40,
    fatG: 0,
    flavor: 'Strawberry & Lime',
    form: 'gel',
    name: 'Beta Fuel Gel',
    notes: '40g carbs with 1:0.8 glucose:fructose ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'beta-fuel-gel-strawberry-lime',
    sodiumMg: 35,
    sugarG: 8
  },
  {
    brandSlug: 'sis',
    caffeineMg: 200,
    calories: 164,
    carbsG: 40,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Beta Fuel Gel + Nootropics',
    notes: 'With caffeine and nootropics',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'beta-fuel-gel-nootropics',
    sodiumMg: 35,
    sugarG: 8
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 148,
    carbsG: 26,
    fatG: 3,
    flavor: 'Chocolate Fudge',
    form: 'bar',
    name: 'GO Energy Bar',
    notes: 'Easy to digest energy bar',
    proteinG: 4,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-energy-bar-chocolate',
    sodiumMg: 25,
    sugarG: 12
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 148,
    carbsG: 26,
    fatG: 3,
    flavor: 'Blueberry',
    form: 'bar',
    name: 'GO Energy Bar',
    notes: 'Easy to digest energy bar',
    proteinG: 4,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-energy-bar-blueberry',
    sodiumMg: 25,
    sugarG: 12
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 148,
    carbsG: 26,
    fatG: 3,
    flavor: 'Red Berry',
    form: 'bar',
    name: 'GO Energy Bar',
    notes: 'Easy to digest energy bar',
    proteinG: 4,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-energy-bar-red-berry',
    sodiumMg: 25,
    sugarG: 12
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 201,
    carbsG: 30,
    fatG: 7,
    flavor: 'Banana',
    form: 'solid',
    name: 'GO Energy Bake',
    notes: 'Filled energy bar',
    proteinG: 4,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-energy-bake-banana',
    sodiumMg: 35,
    sugarG: 17
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 201,
    carbsG: 30,
    fatG: 7,
    flavor: 'Orange',
    form: 'solid',
    name: 'GO Energy Bake',
    notes: 'Filled energy bar',
    proteinG: 4,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-energy-bake-orange',
    sodiumMg: 35,
    sugarG: 17
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 8,
    carbsG: 1,
    fatG: 0,
    flavor: 'Lemon',
    form: 'chew',
    name: 'GO Hydro Tablet',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4.2,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-hydro-tablet-lemon',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 8,
    carbsG: 1,
    fatG: 0,
    flavor: 'Berry',
    form: 'chew',
    name: 'GO Hydro Tablet',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4.2,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-hydro-tablet-berry',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 8,
    carbsG: 1,
    fatG: 0,
    flavor: 'Pineapple & Mango',
    form: 'chew',
    name: 'GO Hydro Tablet',
    notes: 'Zero calorie electrolyte tablet',
    proteinG: 0,
    servingSize: 4.2,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-hydro-tablet-pineapple',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 144,
    carbsG: 36,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'drink_mix',
    name: 'GO Electrolyte Powder',
    notes: 'Energy + electrolytes drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-electrolyte-powder-lemon',
    sodiumMg: 250,
    sugarG: 6
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 144,
    carbsG: 36,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'GO Electrolyte Powder',
    notes: 'Energy + electrolytes drink mix',
    proteinG: 0,
    servingSize: 40,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'go-electrolyte-powder-orange',
    sodiumMg: 250,
    sugarG: 6
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 324,
    carbsG: 80,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Beta Fuel Drink Mix',
    notes: '80g carbs per serving',
    proteinG: 0,
    servingSize: 84,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'beta-fuel-drink-orange',
    sodiumMg: 250,
    sugarG: 15
  },
  {
    brandSlug: 'sis',
    caffeineMg: null,
    calories: 185,
    carbsG: 23,
    fatG: 1,
    flavor: 'Chocolate',
    form: 'powder',
    name: 'REGO Rapid Recovery',
    notes: 'Post-workout recovery shake',
    proteinG: 20,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'rego-recovery-chocolate',
    sodiumMg: 150,
    sugarG: 5
  }
]
