import type { ProductSeedInput } from '../types'

export const skratchLabsProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'Real fruit hydration mix',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-lemon',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Oranges',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'Real fruit hydration mix',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-orange',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Raspberry',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'Real fruit hydration mix',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-raspberry',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Strawberry Lemonade',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'Real fruit hydration mix',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-strawberry',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Pineapple',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'Real fruit hydration mix',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-pineapple',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: 19,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Matcha & Lemon',
    form: 'drink_mix',
    name: 'Sport Hydration Drink Mix',
    notes: 'With natural caffeine',
    proteinG: 0,
    servingSize: 22,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'sport-hydration-mix-matcha',
    sodiumMg: 380,
    sugarG: 16
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 400,
    carbsG: 100,
    fatG: 0,
    flavor: 'Lemon & Lime',
    form: 'drink_mix',
    name: 'Superfuel Drink Mix',
    notes: 'Cluster dextrin for high carb fueling',
    proteinG: 0,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'superfuel-mix-lemon',
    sodiumMg: 800,
    sugarG: 8
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 400,
    carbsG: 100,
    fatG: 0,
    flavor: 'Raspberry',
    form: 'drink_mix',
    name: 'Superfuel Drink Mix',
    notes: 'Cluster dextrin for high carb fueling',
    proteinG: 0,
    servingSize: 55,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'superfuel-mix-raspberry',
    sodiumMg: 800,
    sugarG: 8
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Raspberry',
    form: 'chew',
    name: 'Energy Chews',
    notes: 'Real fruit energy chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-raspberry',
    sodiumMg: 80,
    sugarG: 24
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Orange',
    form: 'chew',
    name: 'Energy Chews',
    notes: 'Real fruit energy chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-orange',
    sodiumMg: 80,
    sugarG: 24
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 160,
    carbsG: 40,
    fatG: 0,
    flavor: 'Sour Cherry',
    form: 'chew',
    name: 'Energy Chews',
    notes: 'Real fruit energy chews',
    proteinG: 0,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chews-sour-cherry',
    sodiumMg: 80,
    sugarG: 24
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 220,
    carbsG: 26,
    fatG: 10,
    flavor: 'Chocolate Chip & Almond',
    form: 'bar',
    name: 'Anytime Energy Bar',
    notes: 'Whole food energy bar',
    proteinG: 6,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'anytime-bar-chocolate',
    sodiumMg: 180,
    sugarG: 12
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 220,
    carbsG: 26,
    fatG: 10,
    flavor: 'Cherry & Pistachio',
    form: 'bar',
    name: 'Anytime Energy Bar',
    notes: 'Whole food energy bar',
    proteinG: 6,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'anytime-bar-cherry',
    sodiumMg: 180,
    sugarG: 12
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 220,
    carbsG: 26,
    fatG: 10,
    flavor: 'Mango & Chili',
    form: 'bar',
    name: 'Anytime Energy Bar',
    notes: 'Whole food energy bar',
    proteinG: 6,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'anytime-bar-mango',
    sodiumMg: 180,
    sugarG: 12
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 180,
    carbsG: 33,
    fatG: 4,
    flavor: 'Chocolate & Mallow',
    form: 'solid',
    name: 'Crispy Rice Cake',
    notes: 'Portable rice cake',
    proteinG: 2,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'crispy-rice-chocolate',
    sodiumMg: 95,
    sugarG: 12
  },
  {
    brandSlug: 'skratch-labs',
    caffeineMg: null,
    calories: 180,
    carbsG: 33,
    fatG: 4,
    flavor: 'Strawberry & Mallow',
    form: 'solid',
    name: 'Crispy Rice Cake',
    notes: 'Portable rice cake',
    proteinG: 2,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'crispy-rice-strawberry',
    sodiumMg: 95,
    sugarG: 12
  }
]
