import type { ProductSeedInput } from '../types'

export const sponserProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 182,
    carbsG: 45,
    fatG: 0,
    flavor: 'Neutral',
    form: 'gel',
    name: 'Liquid Energy Gel',
    notes: 'Liquid gel, easy to consume',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'liquid-energy-gel-neutral',
    sodiumMg: 30,
    sugarG: 23
  },
  {
    brandSlug: 'sponser',
    caffeineMg: 50,
    calories: 182,
    carbsG: 45,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Liquid Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'liquid-energy-gel-cola',
    sodiumMg: 30,
    sugarG: 23
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 182,
    carbsG: 45,
    fatG: 0,
    flavor: 'Peach',
    form: 'gel',
    name: 'Liquid Energy Gel',
    notes: 'Liquid gel, easy to consume',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'liquid-energy-gel-peach',
    sodiumMg: 30,
    sugarG: 23
  },
  {
    brandSlug: 'sponser',
    caffeineMg: 75,
    calories: 182,
    carbsG: 45,
    fatG: 0,
    flavor: 'Mint',
    form: 'gel',
    name: 'Liquid Energy Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'liquid-energy-gel-mint',
    sodiumMg: 30,
    sugarG: 23
  },
  {
    brandSlug: 'sponser',
    caffeineMg: 100,
    calories: 182,
    carbsG: 45,
    fatG: 0,
    flavor: 'Neutral',
    form: 'gel',
    name: 'Liquid Energy Plus Gel',
    notes: 'High caffeine formula',
    proteinG: 0,
    servingSize: 70,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'liquid-energy-plus-gel',
    sodiumMg: 30,
    sugarG: 23
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 180,
    carbsG: 27,
    fatG: 6,
    flavor: 'Hazelnut Chocolate',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Classic energy bar',
    proteinG: 4,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-hazelnut',
    sodiumMg: 20,
    sugarG: 14
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 175,
    carbsG: 28,
    fatG: 5,
    flavor: 'Apricot Vanilla',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Classic energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-apricot',
    sodiumMg: 20,
    sugarG: 15
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 180,
    carbsG: 27,
    fatG: 6,
    flavor: 'Banana Chocolate',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Classic energy bar',
    proteinG: 4,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-banana',
    sodiumMg: 20,
    sugarG: 14
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 228,
    carbsG: 36,
    fatG: 7,
    flavor: 'Banana',
    form: 'solid',
    name: 'Oat Pack',
    notes: 'Oat-based solid fuel',
    proteinG: 5,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'oat-pack-banana',
    sodiumMg: 40,
    sugarG: 12
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 228,
    carbsG: 36,
    fatG: 7,
    flavor: 'Apple',
    form: 'solid',
    name: 'Oat Pack',
    notes: 'Oat-based solid fuel',
    proteinG: 5,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'oat-pack-apple',
    sodiumMg: 40,
    sugarG: 12
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 240,
    carbsG: 34,
    fatG: 9,
    flavor: 'Macadamia Chufas',
    form: 'solid',
    name: 'Oat Pack',
    notes: 'Oat-based solid fuel',
    proteinG: 5,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'oat-pack-macadamia',
    sodiumMg: 40,
    sugarG: 10
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 224,
    carbsG: 56,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Competition',
    notes: 'Competition drink mix',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'competition-orange',
    sodiumMg: 400,
    sugarG: 28
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 224,
    carbsG: 56,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Competition',
    notes: 'Competition drink mix',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'competition-citrus',
    sodiumMg: 400,
    sugarG: 28
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 224,
    carbsG: 56,
    fatG: 0,
    flavor: 'Mixed Berry',
    form: 'drink_mix',
    name: 'Competition',
    notes: 'Competition drink mix',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'competition-mixed-berry',
    sodiumMg: 400,
    sugarG: 28
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 220,
    carbsG: 55,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Long Energy',
    notes: 'Long distance fuel',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'long-energy-citrus',
    sodiumMg: 300,
    sugarG: 25
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 220,
    carbsG: 55,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'Long Energy',
    notes: 'Long distance fuel',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'long-energy-berry',
    sodiumMg: 300,
    sugarG: 25
  },
  {
    brandSlug: 'sponser',
    caffeineMg: 200,
    calories: 20,
    carbsG: 5,
    fatG: 0,
    flavor: 'Cola',
    form: 'liquid',
    name: 'Activator',
    notes: 'High caffeine shot',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'activator-cola',
    sodiumMg: 10,
    sugarG: 3
  },
  {
    brandSlug: 'sponser',
    caffeineMg: 200,
    calories: 20,
    carbsG: 5,
    fatG: 0,
    flavor: 'Citrus',
    form: 'liquid',
    name: 'Activator',
    notes: 'High caffeine shot',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'ml',
    slug: 'activator-citrus',
    sodiumMg: 10,
    sugarG: 3
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'capsule',
    name: 'Salt Caps',
    notes: 'Electrolyte capsules',
    proteinG: 0,
    servingSize: 1.5,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'salt-caps',
    sodiumMg: 250,
    sugarG: 0
  },
  {
    brandSlug: 'sponser',
    caffeineMg: null,
    calories: 0,
    carbsG: 0,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'capsule',
    name: 'Lactat Buffer',
    notes: 'Sodium bicarbonate capsules',
    proteinG: 0,
    servingSize: 3,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'lactat-buffer',
    sodiumMg: 0,
    sugarG: 0
  }
]
