import type { ProductSeedInput } from '../types'

export const springEnergyProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'spring-energy',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Rice & Apple',
    form: 'gel',
    name: 'Awesome Sauce',
    notes: 'Real food gel',
    proteinG: 1,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'awesome-sauce',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: null,
    calories: 190,
    carbsG: 35,
    fatG: 5,
    flavor: 'Peanut Butter & Banana',
    form: 'gel',
    name: 'Speednut',
    notes: 'Real food gel with protein',
    proteinG: 4,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'speednut',
    sodiumMg: 50,
    sugarG: 12
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: 65,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Coffee & Rice',
    form: 'gel',
    name: 'Koffee',
    notes: 'With caffeine',
    proteinG: 1,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'koffee',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Banana & Honey',
    form: 'gel',
    name: 'Hill Aid',
    notes: 'Real food gel',
    proteinG: 1,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hill-aid',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: null,
    calories: 250,
    carbsG: 58,
    fatG: 2,
    flavor: 'Sweet Potato & Coconut',
    form: 'gel',
    name: 'Long Haul',
    notes: 'High calorie gel',
    proteinG: 2,
    servingSize: 72,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'long-haul',
    sodiumMg: 100,
    sugarG: 22
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: null,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Cranberry & Rice',
    form: 'gel',
    name: 'Canberry',
    notes: 'Real food gel',
    proteinG: 1,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'canberry',
    sodiumMg: 50,
    sugarG: 18
  },
  {
    brandSlug: 'spring-energy',
    caffeineMg: 65,
    calories: 180,
    carbsG: 45,
    fatG: 0,
    flavor: 'Cranberry & Rice',
    form: 'gel',
    name: 'Canaberry + Caffeine',
    notes: 'With caffeine',
    proteinG: 1,
    servingSize: 56,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'canberry-caffeine',
    sodiumMg: 50,
    sugarG: 18
  }
]
