import type { ProductSeedInput } from '../types'

export const styrkrProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Citrus',
    form: 'gel',
    name: 'Gel30 Dual-Carb',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel30-citrus',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Berry',
    form: 'gel',
    name: 'Gel30 Dual-Carb',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel30-berry',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Tropical',
    form: 'gel',
    name: 'Gel30 Dual-Carb',
    notes: '30g carbs, 1:0.8 ratio',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel30-tropical',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: 75,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Cola',
    form: 'gel',
    name: 'Gel30 Nitro',
    notes: 'With 75mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel30-nitro-cola',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: 150,
    calories: 113,
    carbsG: 30,
    fatG: 0,
    flavor: 'Mint',
    form: 'gel',
    name: 'Gel30 Nitro',
    notes: 'With 150mg caffeine',
    proteinG: 0,
    servingSize: 60,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'gel30-nitro-mint',
    sodiumMg: 100,
    sugarG: 15
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 240,
    carbsG: 60,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Mix60 Dual-Carb',
    notes: '60g carbs drink mix',
    proteinG: 0,
    servingSize: 65,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'mix60-citrus',
    sodiumMg: 400,
    sugarG: 30
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 240,
    carbsG: 60,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'Mix60 Dual-Carb',
    notes: '60g carbs drink mix',
    proteinG: 0,
    servingSize: 65,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'mix60-berry',
    sodiumMg: 400,
    sugarG: 30
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 360,
    carbsG: 90,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Mix90 Dual-Carb',
    notes: '90g carbs drink mix',
    proteinG: 0,
    servingSize: 95,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'mix90-citrus',
    sodiumMg: 600,
    sugarG: 45
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 200,
    carbsG: 32,
    fatG: 6,
    flavor: 'Chocolate',
    form: 'bar',
    name: 'Bar50',
    notes: '50g bar with balanced carbs',
    proteinG: 4,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'bar50-chocolate',
    sodiumMg: 100,
    sugarG: 16
  },
  {
    brandSlug: 'styrkr',
    caffeineMg: null,
    calories: 200,
    carbsG: 32,
    fatG: 6,
    flavor: 'Salted Caramel',
    form: 'bar',
    name: 'Bar50',
    notes: '50g bar with balanced carbs',
    proteinG: 4,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'bar50-caramel',
    sodiumMg: 100,
    sugarG: 16
  }
]
