import type { ProductSeedInput } from '../types'

export const tailwindNutritionProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Mandarin Orange',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'All-in-one endurance fuel',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-mandarin',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'All-in-one endurance fuel',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-lemon',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Berry',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'All-in-one endurance fuel',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-berry',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Grape',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'All-in-one endurance fuel',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-grape',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: 35,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Raspberry Buzz',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'With 35mg caffeine per serving',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-raspberry',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: 35,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Colorado Cola',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'With 35mg caffeine per serving',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-cola',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: 35,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Tropical Buzz',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'With 35mg caffeine per serving',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-tropical',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 100,
    carbsG: 25,
    fatG: 0,
    flavor: 'Unflavored',
    form: 'drink_mix',
    name: 'Endurance Fuel',
    notes: 'Unflavored option',
    proteinG: 0,
    servingSize: 27,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'endurance-fuel-naked',
    sodiumMg: 303,
    sugarG: 12
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 190,
    carbsG: 32,
    fatG: 2,
    flavor: 'Chocolate',
    form: 'powder',
    name: 'Rebuild Recovery',
    notes: 'Post-workout recovery mix',
    proteinG: 10,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'rebuild-recovery-chocolate',
    sodiumMg: 290,
    sugarG: 14
  },
  {
    brandSlug: 'tailwind-nutrition',
    caffeineMg: null,
    calories: 190,
    carbsG: 32,
    fatG: 2,
    flavor: 'Vanilla',
    form: 'powder',
    name: 'Rebuild Recovery',
    notes: 'Post-workout recovery mix',
    proteinG: 10,
    servingSize: 50,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'rebuild-recovery-vanilla',
    sodiumMg: 290,
    sugarG: 14
  }
]
