import type { ProductSeedInput } from '../types'

export const torqProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Orange',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-orange',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Cherry Bakewell',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-cherry',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Rhubarb & Custard',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-rhubarb',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Apple Crumble',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-apple',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Forest Fruits',
    form: 'gel',
    name: 'Energy Gel',
    notes: 'Natural energy gel',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-forest-fruits',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: 89,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Guarana',
    form: 'gel',
    name: 'Energy Gel Caffeine',
    notes: 'With natural caffeine',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-gel-caffeine-guarana',
    sodiumMg: 50,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 177,
    carbsG: 26,
    fatG: 6,
    flavor: 'Organic Ginger',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Organic energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-organic-ginger',
    sodiumMg: 20,
    sugarG: 13
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 177,
    carbsG: 26,
    fatG: 6,
    flavor: 'Organic Apricot',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Organic energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-organic-apricot',
    sodiumMg: 20,
    sugarG: 13
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 177,
    carbsG: 26,
    fatG: 6,
    flavor: 'Organic Sundried Banana',
    form: 'bar',
    name: 'Energy Bar',
    notes: 'Organic energy bar',
    proteinG: 3,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-bar-organic-sundried',
    sodiumMg: 20,
    sugarG: 13
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Orange',
    form: 'drink_mix',
    name: 'Hydration Drink',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-drink-orange',
    sodiumMg: 200,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 114,
    carbsG: 28,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Hydration Drink',
    notes: 'Isotonic drink mix',
    proteinG: 0,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'hydration-drink-lemon',
    sodiumMg: 200,
    sugarG: 14
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 23,
    carbsG: 5.5,
    fatG: 0,
    flavor: 'Orange',
    form: 'chew',
    name: 'Energy Chew',
    notes: 'Individual energy chew',
    proteinG: 0,
    servingSize: 6,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chew-orange',
    sodiumMg: 10,
    sugarG: 2.8
  },
  {
    brandSlug: 'torq',
    caffeineMg: null,
    calories: 23,
    carbsG: 5.5,
    fatG: 0,
    flavor: 'Cherry',
    form: 'chew',
    name: 'Energy Chew',
    notes: 'Individual energy chew',
    proteinG: 0,
    servingSize: 6,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'energy-chew-cherry',
    sodiumMg: 10,
    sugarG: 2.8
  }
]
