import type { ProductSeedInput } from '../types'

export const untappedProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Original Maple',
    form: 'gel',
    name: 'Maple Syrup Gel',
    notes: 'Pure maple syrup',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'maple-gel-original',
    sodiumMg: 5,
    sugarG: 20
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Salted Maple',
    form: 'gel',
    name: 'Maple Syrup Gel',
    notes: 'With sea salt',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'maple-gel-salted',
    sodiumMg: 100,
    sugarG: 20
  },
  {
    brandSlug: 'untapped',
    caffeineMg: 30,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Coffee Infused',
    form: 'gel',
    name: 'Maple Syrup Gel',
    notes: 'With caffeine',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'maple-gel-coffee',
    sodiumMg: 5,
    sugarG: 20
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Ginger Infused',
    form: 'gel',
    name: 'Maple Syrup Gel',
    notes: 'With ginger',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'maple-gel-ginger',
    sodiumMg: 5,
    sugarG: 20
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 100,
    carbsG: 24,
    fatG: 0,
    flavor: 'Raspberry Infused',
    form: 'gel',
    name: 'Maple Syrup Gel',
    notes: 'With raspberry',
    proteinG: 0,
    servingSize: 28,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'maple-gel-raspberry',
    sodiumMg: 5,
    sugarG: 20
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Lemon',
    form: 'drink_mix',
    name: 'Mapleaid',
    notes: 'Maple-based drink',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'mapleaid-lemon',
    sodiumMg: 200,
    sugarG: 16
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 80,
    carbsG: 20,
    fatG: 0,
    flavor: 'Ginger',
    form: 'drink_mix',
    name: 'Mapleaid',
    notes: 'Maple-based drink',
    proteinG: 0,
    servingSize: 25,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'mapleaid-ginger',
    sodiumMg: 200,
    sugarG: 16
  },
  {
    brandSlug: 'untapped',
    caffeineMg: null,
    calories: 140,
    carbsG: 22,
    fatG: 5,
    flavor: 'Original Maple',
    form: 'solid',
    name: 'Waffle',
    notes: 'Maple waffle',
    proteinG: 2,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-original',
    sodiumMg: 50,
    sugarG: 10
  },
  {
    brandSlug: 'untapped',
    caffeineMg: 30,
    calories: 140,
    carbsG: 22,
    fatG: 5,
    flavor: 'Coffee',
    form: 'solid',
    name: 'Waffle',
    notes: 'With caffeine',
    proteinG: 2,
    servingSize: 30,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'waffle-coffee',
    sodiumMg: 50,
    sugarG: 10
  }
]
