import type { ProductSeedInput } from '../types'

export const veloforteProductSeedData: ProductSeedInput[] = [
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 92,
    carbsG: 22,
    fatG: 0,
    flavor: 'Citrus & Mint',
    form: 'gel',
    name: 'Nectar Energy Gel',
    notes: 'Real food gel',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nectar-gel-citrus',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 92,
    carbsG: 22,
    fatG: 0,
    flavor: 'Blood Orange & Ginger',
    form: 'gel',
    name: 'Nectar Energy Gel',
    notes: 'Real food gel',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nectar-gel-blood-orange',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 92,
    carbsG: 22,
    fatG: 0,
    flavor: 'Rhubarb & Custard',
    form: 'gel',
    name: 'Nectar Energy Gel',
    notes: 'Real food gel',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'nectar-gel-rhubarb',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: 75,
    calories: 92,
    carbsG: 22,
    fatG: 0,
    flavor: 'Mocca',
    form: 'gel',
    name: 'Doppio Energy Gel',
    notes: 'With 75mg caffeine',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'doppio-gel-mocca',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: 40,
    calories: 92,
    carbsG: 22,
    fatG: 0,
    flavor: 'Verde (Matcha)',
    form: 'gel',
    name: 'Doppio Energy Gel',
    notes: 'With matcha caffeine',
    proteinG: 0,
    servingSize: 33,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'doppio-gel-verde',
    sodiumMg: 50,
    sugarG: 16
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 249,
    carbsG: 36,
    fatG: 9,
    flavor: 'Ciocco (Fig & Cacao)',
    form: 'bar',
    name: 'Classico Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'classico-bar-ciocco',
    sodiumMg: 30,
    sugarG: 24
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 249,
    carbsG: 36,
    fatG: 9,
    flavor: 'Zenzero (Ginger & Lemon)',
    form: 'bar',
    name: 'Classico Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'classico-bar-zenzero',
    sodiumMg: 30,
    sugarG: 24
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 249,
    carbsG: 36,
    fatG: 9,
    flavor: 'Di Bosco (Berries)',
    form: 'bar',
    name: 'Classico Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'classico-bar-di-bosco',
    sodiumMg: 30,
    sugarG: 24
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 249,
    carbsG: 36,
    fatG: 9,
    flavor: 'Avena (Apricot & Almond)',
    form: 'bar',
    name: 'Classico Energy Bar',
    notes: 'Natural energy bar',
    proteinG: 5,
    servingSize: 62,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'classico-bar-avena',
    sodiumMg: 30,
    sugarG: 24
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 140,
    carbsG: 35,
    fatG: 0,
    flavor: 'Citrus',
    form: 'chew',
    name: 'Forza Chews',
    notes: 'Natural energy chews',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'forza-chews-citrus',
    sodiumMg: 50,
    sugarG: 25
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 140,
    carbsG: 35,
    fatG: 0,
    flavor: 'Berry',
    form: 'chew',
    name: 'Forza Chews',
    notes: 'Natural energy chews',
    proteinG: 0,
    servingSize: 45,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'forza-chews-berry',
    sodiumMg: 50,
    sugarG: 25
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 25,
    carbsG: 6,
    fatG: 0,
    flavor: 'Citrus',
    form: 'drink_mix',
    name: 'Attivo Electrolyte Powder',
    notes: 'Natural electrolytes',
    proteinG: 0,
    servingSize: 10,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'attivo-electrolyte',
    sodiumMg: 350,
    sugarG: 4
  },
  {
    brandSlug: 'veloforte',
    caffeineMg: null,
    calories: 40,
    carbsG: 10,
    fatG: 0,
    flavor: 'Citrus & Mint',
    form: 'chew',
    name: 'Solo Energy Chew',
    notes: 'Single energy chew',
    proteinG: 0,
    servingSize: 13,
    servingsPerPackage: null,
    servingUnit: 'g',
    slug: 'solo-chew-citrus',
    sodiumMg: 15,
    sugarG: 7
  }
]
